biddr/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :auctions do
    resources :bids
  end
end

biddr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

biddr/app/models/auction.rb
class Auction < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
  validates :reserve_price, presence: true

  has_many :bids, dependent: :destroy

  def new_first_bids
    bids.order(created_at: :desc)
  end
end

biddr/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
end

biddr/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

biddr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

biddr/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
before_action :find_article, only: [:show]
  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new auction_params
    if @auction.save
      flash[:notice] = "Auction Created!"
      redirect_to auction_path(@auction)
    else
      flash[:alert] = "Auction not created!"
      render :new
    end
  end

  def show
    @bid = Bid.new
  end

  private
    def auction_params
      params.require(:auction).permit(:title, :details, :ends_on, :reserve_price)
    end

    def find_article
      @auction = Auction.find params[:id]
    end
end

biddr/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def create
    @bid   = Bid.new bid_params
    @auction = Auction.find params[:auction_id]
    @bid.auction = @auction
    if @bid.save
      redirect_to auction_path(@auction), notice: "Comment created!"
    else
      render "/auction/show"
    end
  end

    private

    def bid_params
      params.require(:bid).permit(:amount)
    end
end

biddr/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

biddr/app/helpers/application_helper.rb
module ApplicationHelper
end

biddr/app/helpers/auctions_helper.rb
module AuctionsHelper
end

biddr/app/helpers/bids_helper.rb
module BidsHelper
end

biddr/app/helpers/home_helper.rb
module HomeHelper
end

biddr/app/views/auctions/new.html.erb
<%= simple_form_for @auction do |f| %>
  <div class="container">
    <p>
      <%= f.input :title %>

    </p>
    <p>
      <%= f.input :details, {rows: "10", cols: "50"}%>
    </p>
      <p>Date: <input type="text" id="datepicker"></p>
    <div>
      <%= f.input :reserve_price, placeholder: "$500" %>
    </div>
    <p>
      <%= f.submit %>
    </p>
  </div>
  <% end %>

biddr/app/views/auctions/show.html.erb
<p>
  <h1><strong><%= @auction.title %></strong></h1>
  <div id="block2">
      Reserve Price : <%= @auction.reserve_price %>
  </div>
</p>
<div >
    <%= @auction.details %>
</div>
<%= simple_form_for [@auction, @bid] do |f| %>
  <div class="container">
    <p>
      <%= f.input :amount %> <%= f.submit %>
    </p>



  </div>
<% end %>
<h3>Previous Bids</h3>
<% @auction.new_first_bids.each do |comms| %>
  $<%= comms.amount %> at <%= comms.created_at.strftime("%B %d %Y") %> <br />
<% end %>

biddr/app/views/home/index.html.erb
<h1>Auction House</h1>

biddr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biddr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script>
$( function() {
  $( "#datepicker" ).datepicker();
} );
</script>
  </head>

  <body>
    <nav>
      <%= link_to "Home", root_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Out", destroy_user_session_path %>


      <%= link_to "New Auction", new_auction_path %>

    </nav>
    <%= yield %>
  </body>
</html>